--- 
server: 
  context-path: /micro
  port: 8080
spring: 
  cloudant: 
    database: customers
    host: "${vcap.services.lightblue-cloudant.credentials.host}"
    password: "${vcap.services.lightblue-cloudant.credentials.password}"
    port: 443
    protocol: https
    username: "${vcap.services.lightblue-cloudant.credentials.username}"
